apiVersion: 1

datasources:
  # Graphite-compatible metrics from Gotel
  - name: Gotel Metrics
    uid: gotel-metrics
    type: graphite
    access: proxy
    url: http://gotel:3200
    isDefault: true
    editable: true
    jsonData:
      graphiteVersion: "1.1"

  # Tempo-compatible traces from Gotel
  - name: Gotel Traces
    uid: gotel-traces
    type: tempo
    access: proxy
    url: http://gotel:3200
    editable: true
    jsonData:
      httpMethod: GET
      enableGrpc: false          # force HTTP/1.1, avoid gRPC preface errors
      grpcEncryption: none
      streamingEnabled:
        search: false
      nodeGraph:
        enabled: true
      search:
        hide: false
